### ISSUE TITLE
Backup funktioniert nicht mehr

### ISSUE THREAD

**Issue by renmet** [jens-maus/hm-ccu-historian#2]
Hallo,

ich habe ein weiteres Problem gefunden. Man kann mit laufendem CCU-HISTORIAN Prozess keine Backups mehr vom Raspberry machen. Grund dürfte wohl ein Out-Of-Memory sein. Eventuell kann man dem Prozess etwas weniger Speicher zuweisen da man sonst immer via SSH den Prozess vor einem Backup killen muss (kill -9 PID).

LG

**Comment by jens-maus** [comment]
Das ist nicht nur ein Problem des limitierten Arbeitsspeichers des RaspberryPi sondern auch der sehr limitierten Backuproutinen von RaspberryMatic die das Backup temporär in das /var filesystem legen und das selbst auch im Verhältnis zu /usr/local zu klein ist. 

Alles in allem ist das Thema Backup bei RaspberryMatic/CCU ein Problem das man denke ich nur durch von der WebUI getrennten Routinen erledigen kann. Ich wüsste also nicht wie ich dieses Problem im Bezug auf CCU-Historian lösen sollte.

**Comment by renmet** [comment]
Hallo,

sprich wenn Backup dann mit Cuxd im Moment? Ok werde ich probieren. Leider hatte ich mit den Cuxd Backups schon mal Probleme beim Recovern. Mach das Issue einfach zu.

Danke für deine rasche Antwort.

LG
