### ISSUE TITLE
Historian startet nicht

### ISSUE THREAD

**Issue by raintausdu** [jens-maus/hm-ccu-historian#3]
Hi,

nach der Installation komme ich nicht auf die konfigwebsite. 
In welchem logfile kann ich sehen ob der Dienst läuft?

Danke
Gruß

**Comment by jens-maus** [comment]
Unter ```/var/log```solltest du eine/mehrere Dateien finden die "ccu-historian-X.log" heissen, wobei X dann eine Zahl ist.

**Comment by raintausdu** [comment]
Hallo Jens - 
danke für die schnelle Hilfe.

Im Log wurde bei mir auch: Exception: IO Exception - mit dem raspberryNamen  protokolliert.
Ich habe den Namen auf der FritzBox eingetragen und den Raspi neugestartet.
Die IO Exeption ist nun weg - auf die Webseite komme ich nur über die IP Adresse + Port.

Das heißt die Namensauflösung der FritzBox funktioniert nicht.
OK - auch das ist gelöst. 
In dem WebUI muss an den Namen noch Fritz.box gehängt werden- dann klappt es.

Soweit ist das Problem ja gelöst.
Jetzt streikt noch der Link zur "Datenbank" - http://IP-Adresse:8083 
Wieso wird da die Webseite dann über die IP aufgerufen?

Tausend dank

Gruß

**Comment by raintausdu** [comment]
OK - im Configfile habe ich auch das 'Problem' mit der Datenbank gefunden.

Du kannst das issue schließen - 

danke

**Comment by jens-maus** [comment]
Ok. ich schliesse es. Standardmäßig habe ich eben den webserver der Datenbank abgeschalten. den brauch man IMHO wirklich eigentlich bzw. nur sehr selten. Dann viel Spass damit!
